[package]
name = "hextral"
version = "0.3.5"
authors = ["xStFtx <noskillz.exe@gmail.com>"]
description = "Six dimensional Neural Network testing. Has Laplace and quantum fourier transform capabilities."
license = "MIT/Apache-2.0"

[dependencies]
nalgebra = "0.32"
rand = "0.8"
num-traits = "0.2"

[lib]
name = "hextral"
repository = "https://github.com/xStFtx/hextral"
