[package]
name = "hextral"
version = "0.4.0"
authors = ["xStFtx <noskillz.exe@gmail.com>"]
description = "Advanced neural network library with batch normalization, multiple optimizers, and regularization techniques"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xStFtx/hextral"
keywords = ["neural-network", "machine-learning", "deep-learning", "ai", "optimization"]
categories = ["algorithms", "mathematics", "science"]
edition = "2021"
readme = "README.md"

[dependencies]
nalgebra = "0.33"
rand = { version = "0.8", features = ["std_rng"] }
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde", "nalgebra/serde-serialize"]

[lib]
name = "hextral"
